//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace HotelMobiModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HotelMobiEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HotelMobiEntities object using the connection string found in the 'HotelMobiEntities' section of the application configuration file.
        /// </summary>
        public HotelMobiEntities() : base("name=HotelMobiEntities", "HotelMobiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HotelMobiEntities object.
        /// </summary>
        public HotelMobiEntities(string connectionString) : base(connectionString, "HotelMobiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HotelMobiEntities object.
        /// </summary>
        public HotelMobiEntities(EntityConnection connection) : base(connection, "HotelMobiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dish> Dishes
        {
            get
            {
                if ((_Dishes == null))
                {
                    _Dishes = base.CreateObjectSet<Dish>("Dishes");
                }
                return _Dishes;
            }
        }
        private ObjectSet<Dish> _Dishes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Dishes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDishes(Dish dish)
        {
            base.AddObject("Dishes", dish);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HotelMobiModel", Name="Dish")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dish : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dish object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="ingredients">Initial value of the Ingredients property.</param>
        /// <param name="category">Initial value of the Category property.</param>
        /// <param name="subCategory">Initial value of the SubCategory property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        /// <param name="timeTaken">Initial value of the TimeTaken property.</param>
        /// <param name="insertedAt">Initial value of the InsertedAt property.</param>
        /// <param name="updatedAt">Initial value of the UpdatedAt property.</param>
        public static Dish CreateDish(global::System.Int32 id, global::System.String name, global::System.String description, global::System.String ingredients, global::System.String category, global::System.String subCategory, global::System.Decimal price, global::System.Int32 timeTaken, global::System.DateTime insertedAt, global::System.DateTime updatedAt)
        {
            Dish dish = new Dish();
            dish.Id = id;
            dish.Name = name;
            dish.Description = description;
            dish.Ingredients = ingredients;
            dish.Category = category;
            dish.SubCategory = subCategory;
            dish.Price = price;
            dish.TimeTaken = timeTaken;
            dish.InsertedAt = insertedAt;
            dish.UpdatedAt = updatedAt;
            return dish;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ingredients
        {
            get
            {
                return _Ingredients;
            }
            set
            {
                OnIngredientsChanging(value);
                ReportPropertyChanging("Ingredients");
                _Ingredients = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ingredients");
                OnIngredientsChanged();
            }
        }
        private global::System.String _Ingredients;
        partial void OnIngredientsChanging(global::System.String value);
        partial void OnIngredientsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SubCategory
        {
            get
            {
                return _SubCategory;
            }
            set
            {
                OnSubCategoryChanging(value);
                ReportPropertyChanging("SubCategory");
                _SubCategory = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SubCategory");
                OnSubCategoryChanged();
            }
        }
        private global::System.String _SubCategory;
        partial void OnSubCategoryChanging(global::System.String value);
        partial void OnSubCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TimeTaken
        {
            get
            {
                return _TimeTaken;
            }
            set
            {
                OnTimeTakenChanging(value);
                ReportPropertyChanging("TimeTaken");
                _TimeTaken = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeTaken");
                OnTimeTakenChanged();
            }
        }
        private global::System.Int32 _TimeTaken;
        partial void OnTimeTakenChanging(global::System.Int32 value);
        partial void OnTimeTakenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime InsertedAt
        {
            get
            {
                return _InsertedAt;
            }
            set
            {
                OnInsertedAtChanging(value);
                ReportPropertyChanging("InsertedAt");
                _InsertedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InsertedAt");
                OnInsertedAtChanged();
            }
        }
        private global::System.DateTime _InsertedAt;
        partial void OnInsertedAtChanging(global::System.DateTime value);
        partial void OnInsertedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedAt
        {
            get
            {
                return _UpdatedAt;
            }
            set
            {
                OnUpdatedAtChanging(value);
                ReportPropertyChanging("UpdatedAt");
                _UpdatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedAt");
                OnUpdatedAtChanged();
            }
        }
        private global::System.DateTime _UpdatedAt;
        partial void OnUpdatedAtChanging(global::System.DateTime value);
        partial void OnUpdatedAtChanged();

        #endregion

    
    }

    #endregion

    
}
